language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - "pip install pygments"

branches:
  only:
    - master

script:
  - "pip install git+https://github.com/satreix/pygments-github-lexers@master"
